// src/lib/metadata.ts
// Single Source of Truth for Tables, Columns, Relationships, and Search in AIU V2

import {
  TableName,
  TableMetadata,
  RelationshipMetadata,
  SearchMetadata,
  OutputFieldOption,
} from './types';

export const TABLES_METADATA: Record<TableName, TableMetadata> = {
  user_details: {
    id: 'user_details',
    displayName: 'User Details',
    description: 'Core client user records, trading segment permissions, and update dates.',
    primaryKey: ['client_code'],
    displayColumns: ['client_code', 'user_id', 'user_account_status_flag', 'user_first_active_date', 'user_equity_allowed'],
    columns: [
      { name: 'user_id', dataType: 'TEXT', description: 'Internal user system identifier' },
      { name: 'client_code', dataType: 'TEXT', isPrimaryKey: true, description: 'Primary business key' },
      { name: 'user_account_status_flag', dataType: 'TEXT', defaultVisible: true, description: 'Account status (ACTIVE/SUSPENDED/etc)' },
      { name: 'user_update_date', dataType: 'DATE', description: 'Last account update date' },
      { name: 'user_equity_allowed', dataType: 'TEXT', defaultVisible: true, description: 'Equity segment flag' },
      { name: 'user_mf_allowed', dataType: 'TEXT', defaultVisible: true, description: 'Mutual fund flag' },
      { name: 'user_fno_allowed', dataType: 'TEXT', defaultVisible: true, description: 'Futures & options flag' },
      { name: 'user_commodity_allowed', dataType: 'TEXT', description: 'Commodity trading flag' },
      { name: 'user_ipo_allowed', dataType: 'TEXT', description: 'IPO application flag' },
      { name: 'user_loan_allowed', dataType: 'TEXT', description: 'Loan against shares flag' },
      { name: 'user_first_active_date', dataType: 'DATE', defaultVisible: true, description: 'First trading activation date' },
      { name: 'data', dataType: 'JSONB', description: 'Complete source Excel row snapshot' },
    ],
  },

  user_account_information: {
    id: 'user_account_information',
    displayName: 'User Account Information',
    description: 'Banking credentials, demat registration, branch codes, and form mapping.',
    primaryKey: ['form_number'],
    displayColumns: ['form_number', 'client_code', 'user_bank_type', 'user_bank_account_number', 'user_demat_account_open_date'],
    columns: [
      { name: 'form_number', dataType: 'BIGINT', isPrimaryKey: true, defaultVisible: true, description: 'Unique physical/electronic form number' },
      { name: 'client_code', dataType: 'TEXT', isForeignKey: true, fkTarget: { table: 'user_details', column: 'client_code' }, defaultVisible: true, description: 'Reference to User Details' },
      { name: 'user_type_residential_nri', dataType: 'TEXT', description: 'Residential status (RESIDENT / NRI)' },
      { name: 'user_bank_account_number', dataType: 'TEXT', defaultVisible: true, description: 'Bank account number' },
      { name: 'user_bank_customer_id', dataType: 'TEXT', description: 'Core banking customer ID' },
      { name: 'user_bank_brnch_code', dataType: 'TEXT', description: 'Branch IFSC/Branch identifier' },
      { name: 'user_bank_account_type_self_joint', dataType: 'TEXT', description: 'Account holding structure' },
      { name: 'user_bank_account_open_date', dataType: 'DATE', description: 'Bank account opening date' },
      { name: 'user_demat_account_open_date', dataType: 'DATE', defaultVisible: true, description: 'Demat account opening date' },
      { name: 'user_info_entered_by', dataType: 'TEXT', description: 'Data entry officer ID' },
      { name: 'user_info_modified_by', dataType: 'TEXT', description: 'Modification officer ID' },
      { name: 'user_info_modified_date', dataType: 'TIMESTAMPTZ', description: 'Last modification timestamp' },
      { name: 'user_bank_account_flag', dataType: 'TEXT', description: 'Bank status flag' },
      { name: 'user_bank_type', dataType: 'TEXT', defaultVisible: true, description: 'Type of banking institution' },
      { name: 'data', dataType: 'JSONB', description: 'Complete source Excel row snapshot' },
    ],
  },

  user_address_details: {
    id: 'user_address_details',
    displayName: 'User Address Details',
    description: 'Contact coordinates, correspondence addresses, mobile numbers, and IP audit trails.',
    primaryKey: ['form_number'],
    displayColumns: ['form_number', 'user_mobile_number', 'user_city', 'user_state', 'user_pin'],
    columns: [
      { name: 'form_number', dataType: 'BIGINT', isForeignKey: true, fkTarget: { table: 'user_account_information', column: 'form_number' }, defaultVisible: true, description: 'Form number linkage' },
      { name: 'address_type_correspondance_permanent', dataType: 'TEXT', description: 'Address category' },
      { name: 'address_1', dataType: 'TEXT', description: 'Line 1 address' },
      { name: 'address_2', dataType: 'TEXT', description: 'Line 2 address' },
      { name: 'user_city', dataType: 'TEXT', defaultVisible: true, description: 'City' },
      { name: 'user_state', dataType: 'TEXT', defaultVisible: true, description: 'State' },
      { name: 'user_country', dataType: 'TEXT', description: 'Country' },
      { name: 'user_pin', dataType: 'TEXT', defaultVisible: true, description: 'Postal PIN code' },
      { name: 'user_telephone_number', dataType: 'TEXT', description: 'Landline number' },
      { name: 'user_office_number', dataType: 'TEXT', description: 'Office contact number' },
      { name: 'user_mobile_number', dataType: 'TEXT', defaultVisible: true, description: 'Auditable mobile contact number' },
      { name: 'user_mail_address_flag', dataType: 'TEXT', description: 'Physical mail delivery indicator' },
      { name: 'user_details_entered_by', dataType: 'TEXT', description: 'Entry operator ID' },
      { name: 'user_details_entry_date', dataType: 'TIMESTAMPTZ', description: 'Entry timestamp' },
      { name: 'user_details_modified_by', dataType: 'TEXT', description: 'Modification operator' },
      { name: 'user_details_modified_date', dataType: 'TIMESTAMPTZ', description: 'Modification timestamp' },
      { name: 'user_address_same_as_correspondance', dataType: 'TEXT', description: 'Same as correspondence flag' },
      { name: 'user_ip', dataType: 'TEXT', description: 'Audit submission IP address' },
      { name: 'user_mobile_relation', dataType: 'TEXT', description: 'Mobile owner relation' },
      { name: 'user_rm_preferred_location_pin', dataType: 'TEXT', description: 'RM serviced location PIN' },
      { name: 'data', dataType: 'JSONB', description: 'Complete source Excel row snapshot' },
    ],
  },

  user_personal_details: {
    id: 'user_personal_details',
    displayName: 'User Personal Details',
    description: 'Demographics, names, email, Aadhar verification, nationality, and KYC details.',
    primaryKey: ['form_number'],
    displayColumns: ['form_number', 'user_first_name', 'user_last_name', 'user_email', 'user_dob', 'user_customer_type'],
    columns: [
      { name: 'form_number', dataType: 'BIGINT', isForeignKey: true, fkTarget: { table: 'user_account_information', column: 'form_number' }, defaultVisible: true, description: 'Form number linkage' },
      { name: 'user_type_applicant_permanent', dataType: 'TEXT', description: 'Applicant designation' },
      { name: 'user_first_name', dataType: 'TEXT', defaultVisible: true, description: 'Applicant first name' },
      { name: 'user_middle_name', dataType: 'TEXT', description: 'Applicant middle name' },
      { name: 'user_last_name', dataType: 'TEXT', defaultVisible: true, description: 'Applicant surname' },
      { name: 'user_dob', dataType: 'DATE', defaultVisible: true, description: 'Date of birth' },
      { name: 'user_sex', dataType: 'TEXT', description: 'Gender' },
      { name: 'user_minor_flag', dataType: 'TEXT', description: 'Minor investor flag' },
      { name: 'user_email', dataType: 'TEXT', defaultVisible: true, description: 'Registered email address' },
      { name: 'user_country_birth', dataType: 'TEXT', description: 'Birth country' },
      { name: 'user_nationality', dataType: 'TEXT', description: 'Investor nationality' },
      { name: 'user_entered_employee_number', dataType: 'TEXT', description: 'KYC sourcing employee ID' },
      { name: 'user_details_entered_date', dataType: 'TIMESTAMPTZ', description: 'Creation timestamp' },
      { name: 'user_details_modified_employee_number', dataType: 'TEXT', description: 'Updating officer ID' },
      { name: 'userd_details_modified_date', dataType: 'TIMESTAMPTZ', description: 'Last revision timestamp' },
      { name: 'user_designation', dataType: 'TEXT', description: 'Occupation / Designation' },
      { name: 'user_relation', dataType: 'TEXT', description: 'Family relation' },
      { name: 'user_user_id', dataType: 'TEXT', description: 'System User ID' },
      { name: 'user_income_category', dataType: 'TEXT', description: 'Annual income bracket' },
      { name: 'user_marital_status', dataType: 'TEXT', description: 'Marital status' },
      { name: 'user_political_connect', dataType: 'TEXT', description: 'Politically exposed person (PEP)' },
      { name: 'user_inperson_verification_date', dataType: 'DATE', description: 'IPV verification date' },
      { name: 'user_customer_type', dataType: 'TEXT', defaultVisible: true, description: 'Customer classification' },
      { name: 'user_update_ip', dataType: 'TEXT', description: 'Profile modification IP' },
      { name: 'user_update_channel', dataType: 'TEXT', description: 'Digital/Branch channel' },
      { name: 'user_us_person', dataType: 'TEXT', description: 'FATCA US Person flag' },
      { name: 'user_tax_filing_country', dataType: 'TEXT', description: 'Tax residency country' },
      { name: 'user_place_of_birth', dataType: 'TEXT', description: 'Birthplace city' },
      { name: 'user_email_relation', dataType: 'TEXT', description: 'Email address owner' },
      { name: 'user_aadhar_last_4_digit', dataType: 'TEXT', defaultVisible: true, description: 'Masked Aadhar digits' },
      { name: 'user_name_as_per_aadhar', dataType: 'TEXT', description: 'Aadhar registered legal name' },
      { name: 'user_aadhar_status', dataType: 'TEXT', description: 'Aadhar authentication status' },
      { name: 'user_aadhar_consent_flag', dataType: 'TEXT', description: 'Aadhar consent documentation' },
      { name: 'data', dataType: 'JSONB', description: 'Complete source Excel row snapshot' },
    ],
  },

  client_details: {
    id: 'client_details',
    displayName: 'Client Details',
    description: 'Inward verification, PAN records, agent sourcing, agreements, and settlement tiers.',
    primaryKey: ['client_code', 'form_number'],
    displayColumns: ['client_code', 'form_number', 'client_pan_number', 'client_verify_status', 'client_product_type'],
    columns: [
      { name: 'form_number', dataType: 'BIGINT', isForeignKey: true, fkTarget: { table: 'user_account_information', column: 'form_number' }, defaultVisible: true, description: 'Form linkage' },
      { name: 'client_code', dataType: 'TEXT', isForeignKey: true, fkTarget: { table: 'user_details', column: 'client_code' }, defaultVisible: true, description: 'Client code linkage' },
      { name: 'customer_type_individual_huf', dataType: 'TEXT', description: 'Constitution category' },
      { name: 'client_inward_date', dataType: 'DATE', description: 'Docket inward date' },
      { name: 'client_scheme_type', dataType: 'TEXT', description: 'Client brokerage plan' },
      { name: 'client_inward_status', dataType: 'TEXT', description: 'Inward acceptance state' },
      { name: 'client_inward_accept_date', dataType: 'DATE', description: 'Acceptance timestamp' },
      { name: 'client_agreement_date', dataType: 'DATE', description: 'Signed agreement date' },
      { name: 'client_agent_code', dataType: 'TEXT', description: 'Franchisee / Agent code' },
      { name: 'client_sub_agent_code', dataType: 'TEXT', description: 'Sub-agent reference' },
      { name: 'client_product_type', dataType: 'TEXT', defaultVisible: true, description: 'Product classification' },
      { name: 'client_icici_emp_number', dataType: 'TEXT', description: 'Relationship manager employee code' },
      { name: 'client_receipt_date', dataType: 'DATE', description: 'Cheque/Doc receipt date' },
      { name: 'client_form_version', dataType: 'TEXT', description: 'Form template version' },
      { name: 'client_user_id', dataType: 'TEXT', description: 'System client user ID' },
      { name: 'client_web_user_id', dataType: 'TEXT', description: 'Web login identity' },
      { name: 'client_marital_status', dataType: 'TEXT', description: 'Marital record' },
      { name: 'client_education_code', dataType: 'TEXT', description: 'Educational qualification' },
      { name: 'client_income_category_code', dataType: 'TEXT', description: 'Income bracket index' },
      { name: 'client_holding_range_code', dataType: 'TEXT', description: 'Investment networth bracket' },
      { name: 'client_customer_nri_flag', dataType: 'TEXT', description: 'NRI investor indicator' },
      { name: 'client_form_60_flag', dataType: 'TEXT', description: 'Form 60/61 submission' },
      { name: 'client_tax_assesse_flag', dataType: 'TEXT', description: 'Income tax assessee flag' },
      { name: 'client_verification_date', dataType: 'DATE', description: 'Audit verification date' },
      { name: 'client_verify_status', dataType: 'TEXT', defaultVisible: true, description: 'KYC & Audit verification status' },
      { name: 'client_ack_flag', dataType: 'TEXT', description: 'Client acknowledgement dispatched' },
      { name: 'client_ack_date', dataType: 'DATE', description: 'Dispatch date' },
      { name: 'client_send_mail_flag', dataType: 'TEXT', description: 'Welcome kit mail flag' },
      { name: 'client_eba_upload_flag', dataType: 'TEXT', description: 'Exchange registration upload status' },
      { name: 'client_eba_upload_date', dataType: 'DATE', description: 'Exchange upload date' },
      { name: 'client_last_flag', dataType: 'TEXT', description: 'Historical record indicator' },
      { name: 'client_rejection_mail_remarks', dataType: 'TEXT', description: 'Discrepancy remarks if rejected' },
      { name: 'client_details_entered_by', dataType: 'TEXT', description: 'Registration officer' },
      { name: 'client_details_entry_date', dataType: 'TIMESTAMPTZ', description: 'Creation date' },
      { name: 'client_details_modified_by', dataType: 'TEXT', description: 'Modification officer' },
      { name: 'client_details_modified_date', dataType: 'TIMESTAMPTZ', description: 'Modification date' },
      { name: 'client_pan_number', dataType: 'TEXT', defaultVisible: true, description: 'Permanent Account Number (PAN)' },
      { name: 'client_category_employee_code', dataType: 'TEXT', description: 'Employee category code' },
      { name: 'client_rm_code', dataType: 'TEXT', description: 'Assigned RM code' },
      { name: 'client_nri_category_type', dataType: 'TEXT', description: 'NRI tier category' },
      { name: 'client_nri_base_scheme', dataType: 'TEXT', description: 'NRI fee scheme' },
      { name: 'client_nri_current_scheme', dataType: 'TEXT', description: 'NRI active scheme' },
      { name: 'client_non_isec_agent_code', dataType: 'TEXT', description: 'External broker agent code' },
      { name: 'client_customer_type_change_date', dataType: 'DATE', description: 'Re-classification date' },
      { name: 'client_bank_type', dataType: 'TEXT', description: 'Associated bank tie-in' },
      { name: 'client_settlement_type', dataType: 'TEXT', description: 'Settlement frequency (MONTHLY/QUARTERLY)' },
      { name: 'client_demat_mandate_category', dataType: 'TEXT', description: 'Standing instruction mandate' },
      { name: 'client_brokerage_model_flag', dataType: 'TEXT', description: 'Discount / Full-service model' },
      { name: 'data', dataType: 'JSONB', description: 'Complete source Excel row snapshot' },
    ],
  },
};

export const RELATIONSHIPS_METADATA: RelationshipMetadata[] = [
  {
    id: 'R1',
    code: 'R1',
    parentTable: 'user_details',
    parentKey: 'client_code',
    childTable: 'user_account_information',
    childKey: 'client_code',
    description: 'User Details.Client Code → User Account Information.Client Code',
    cardinality: '1:1',
  },
  {
    id: 'R2',
    code: 'R2',
    parentTable: 'user_details',
    parentKey: 'client_code',
    childTable: 'client_details',
    childKey: 'client_code',
    description: 'User Details.Client Code → Client Details.Client Code',
    cardinality: '1:1',
  },
  {
    id: 'R3',
    code: 'R3',
    parentTable: 'user_account_information',
    parentKey: 'form_number',
    childTable: 'user_address_details',
    childKey: 'form_number',
    description: 'User Account Information.Form Number → User Address Details.Form Number',
    cardinality: '1:1',
  },
  {
    id: 'R4',
    code: 'R4',
    parentTable: 'user_account_information',
    parentKey: 'form_number',
    childTable: 'user_personal_details',
    childKey: 'form_number',
    description: 'User Account Information.Form Number → User Personal Details.Form Number',
    cardinality: '1:1',
  },
  {
    id: 'R5',
    code: 'R5',
    parentTable: 'user_account_information',
    parentKey: 'form_number',
    childTable: 'client_details',
    childKey: 'form_number',
    description: 'User Account Information.Form Number → Client Details.Form Number',
    cardinality: '1:1',
  },
];

export const SEARCH_METADATA: Record<string, SearchMetadata> = {
  mobile: {
    type: 'mobile',
    label: 'Mobile Number',
    placeholder: 'Enter 10-digit mobile (e.g. 9820123401)',
    description: 'Retrieves user_address_details and traverses Form Number & Client Code chains',
    sourceTable: 'user_address_details',
    sourceColumn: 'user_mobile_number',
    matchMethod: 'exact',
    exampleValue: '9820123401',
  },
  pan: {
    type: 'pan',
    label: 'PAN Number',
    placeholder: 'Enter 10-char PAN (e.g. ABCDE1234F)',
    description: 'Retrieves client_details and traverses Client Code & Form Number chains',
    sourceTable: 'client_details',
    sourceColumn: 'client_pan_number',
    matchMethod: 'exact',
    exampleValue: 'ABCDE1234F',
  },
  client_code: {
    type: 'client_code',
    label: 'Client Code',
    placeholder: 'Enter Client Code (e.g. CL00101)',
    description: 'Searches user_details, user_account_information, client_details and traverses relationships',
    sourceTable: 'user_details',
    sourceColumn: 'client_code',
    matchMethod: 'exact',
    exampleValue: 'CL00101',
  },
  form_number: {
    type: 'form_number',
    label: 'Form Number',
    placeholder: 'Enter Form Number (e.g. 1000000001)',
    description: 'Searches form_number (BIGINT) across account, address, personal & client details',
    sourceTable: 'user_account_information',
    sourceColumn: 'form_number',
    matchMethod: 'exact',
    exampleValue: '1000000001',
  },
  name: {
    type: 'name',
    label: 'Client Name',
    placeholder: 'Enter full or partial name (e.g. Rahul, Sharma)',
    description: 'Case-insensitive partial matching across first, middle, or last name',
    sourceTable: 'user_personal_details',
    sourceColumn: 'user_first_name',
    matchMethod: 'partial',
    exampleValue: 'Rahul',
  },
};

export const COMMON_OUTPUT_FIELDS: OutputFieldOption[] = [
  { id: 'client_code', table: 'user_details', column: 'client_code', label: 'Client Code', dataType: 'TEXT', defaultSelected: true },
  { id: 'form_number', table: 'user_account_information', column: 'form_number', label: 'Form Number', dataType: 'BIGINT', defaultSelected: true },
  { id: 'client_pan_number', table: 'client_details', column: 'client_pan_number', label: 'PAN', dataType: 'TEXT', defaultSelected: true },
  { id: 'user_mobile_number', table: 'user_address_details', column: 'user_mobile_number', label: 'Mobile Number', dataType: 'TEXT', defaultSelected: true },
  { id: 'user_name', table: 'user_personal_details', column: 'user_first_name', label: 'Name', dataType: 'TEXT', defaultSelected: true },
  { id: 'user_account_status_flag', table: 'user_details', column: 'user_account_status_flag', label: 'Account Status', dataType: 'TEXT', defaultSelected: true },
  { id: 'client_verify_status', table: 'client_details', column: 'client_verify_status', label: 'Client Status', dataType: 'TEXT', defaultSelected: true },
  { id: 'user_state', table: 'user_address_details', column: 'user_state', label: 'State', dataType: 'TEXT', defaultSelected: true },
  { id: 'user_city', table: 'user_address_details', column: 'user_city', label: 'City', dataType: 'TEXT', defaultSelected: false },
  { id: 'user_email', table: 'user_personal_details', column: 'user_email', label: 'Email', dataType: 'TEXT', defaultSelected: false },
  { id: 'user_bank_type', table: 'user_account_information', column: 'user_bank_type', label: 'Bank Type', dataType: 'TEXT', defaultSelected: false },
  { id: 'user_equity_allowed', table: 'user_details', column: 'user_equity_allowed', label: 'Equity Allowed', dataType: 'TEXT', defaultSelected: false },
];
